kind: Namespace
apiVersion: v1
metadata:
  name: database-controller

---

kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: database-controller
  name: controller

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: database-controller
rules:
- apiGroups:
  - kubejam
  resources:
  - databases
  - databases.kubejam
  verbs:
  - create
  - update
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - create
  - update
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: database-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: database-controller
subjects:
- kind: ServiceAccount
  name: controller
  namespace: database-controller

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: database-controller
  name: controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccount: controller
      volumes:
      - name: config
        secret:
          secretName: config
      containers:
      - name: controller
        image: kubejam/database-controller:v1.0.0-alpha6
        args:
        - --config=/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi

